client_config_backend: settings
client_config:
  client_id: 52552816616-f2q3qlu26j7hci67k0rcc2387hu9i13u.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive